- name: Install Java
  package: 
    name: java
    state: installed
  
- name: Add Application user
  user:
    name: "{{APPUSER}}"
    comment: "application user"

- name: Download & Extract Tomcat
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "{{APPUSERHOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Find old dir's
  find: 
    paths: "{{TOMCATDIR}}/webapps"
    file_type: any
  register: out

- name: Remove old webapps
  file:
    path: "{{item.path}}"
    state: absent
  loop: "{{out.files}}"

- name: Download WAR file
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{TOMCATDIR}}/webapps/student.war"
  become_user: "{{APPUSER}}"

- name: Download JDBC jar file
  get_url:
    url: "{{JAR_URL}}"
    dest: "{{TOMCATDIR}}/lib/mysql-connector.jar"
  become_user: "{{APPUSER}}"

  - name: copy context.xml
    template:
      src: context.xml
      dest: "{{TOMCATDIR}}/conf/context.xml"
    become_user: "{{APPUSER}}"

  - name: Update tomcat init script
    template:
        src: studentapp-init
        dest: /etc/init.d/tomcat
        mode: 0755

  - name: Reload systemctld
    shell: systemctl daemon-reload

  - name: Start tomcat service
    service:
        name: tomcat
        state: started
        enabled: yes
