- name: Conditions
  hosts: all
  vars:
   epic: no
  tasks:
    - name: Run when OS is centos
      debug:
        msg: Hello centos
      when: ansible_distribution == "CentOS"

    - name: Run when OS is centos
      debug:
        msg: Hello Ubuntu
      when: ansible_distribution == "Debain"
    - name: Run an action
      debug:
        msg: Hello Action SAHOO
      when: epic
