- name: Demo on Facts
  hosts: all
  gather_facts: true
  tasks:
    - name: Print Hello
      debug:
        msg: Hello World
    - name: Print OS distribution
      debug:
        msg: OS_d = {{ansible_distribution}}