- hosts: all
  vars:
    URL: http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.45/bin/apache-tomcat-8.5.45.tar.gz
    FILE: "{{ URL.split('/') | last }}"
    DIR: "{{FILE | regex_replace('.tar.gz', ''}}"
  tasks:
    - debug: msg="{{DIR}}"