- name: Find files in directory and remove
#student war files need to check if it is already there.
  hosts: all
  tasks:
    - name: Find the files
      find:
        paths: /tmp/demo
        recurse: yes
      register: out
      
    - debug: msg="{{out}}"
