- name: Setup nginx package
  hosts: all
  become: yes
  tasks:
    - name: Installing nginx
      yum:
        name: nginx
        state: present
    - name: Checking nginx running or not
      service:
        name: nginx
        state: started