- name: Demo on reg-vars
  hosts: all
  tasks:
    - name: Run shell command
      shell: uptime
      register: OUT

    - name: Print OUT variable
      debug:
        msg: "{{OUT}}"
        
      
