- name: Remove apache package
  hosts: all
  become: yes
  tasks:
    - name: stop apache
      yum:
        name: httpd
        state: absent
    - name: Checking httpd running or not
      service:
        name: httpd
        state: stopped