- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{URL}}

    - name: Print URL from task
      debug: 
        msg: URL = {{URL}}
      vars:
        URL: task.google.com

    - name: Print URL from CLI
      debug:
        msg: URL_CLI = {{URL_CLI}}

    